import "./globals.css";
import { Inter, Poppins } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const poppins = Poppins({
  weight: ['400', '700'],  
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
})

export const metadata = {
  title: "Agent 4 Hire | Home",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en' className={`${inter.variable} ${poppins.variable}`}>
      <body className={`${inter.className} font-sans`}>{children}</body>
    </html>
  );
}

