import "./globals.css";
import {Poppins} from "next/font/google"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const poppins_init = Poppins(
	{
		subsets: ["latin"],
		display: "swap",
		variable: '--font-poppins',
		weight: ['100','200','300','400','500','600','700','800','900']
	}
)

export default function RootLayout({children}) {
	return (
		<html lang='en'>
			<body className={`poppins_init.variable`}>{children}</body>
		</html>
	);
}
