import { CustomSidebar } from "@/components/Sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function DashboardLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<body className="flex gap-4 h-screen">
                <SidebarProvider>

                <CustomSidebar/>
                </SidebarProvider>
                {children}
                </body>
		</html>
	);
}
