import DashboardNavbar from "@/components/DashboardNavbar";
import Navbar from "@/components/Navbar";
import { CustomSidebar } from "@/components/Sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function DashboardLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<body className="flex h-screen w-full">
				<div className="w-max ">
					<SidebarProvider>
						<CustomSidebar/>
					</SidebarProvider>
				</div>
				<div className="flex flex-col gap-2 w-full ">
					<DashboardNavbar />
                {children}

				</div>


                </body>
		</html>
	);
}
